file:
  upload-dir: C:\BEYOND #${UPLOAD_PATH}
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: root #${DB_USER}
    password: qwer1234 #${DB_PASSWORD}
    url: jdbc:mariadb://10.10.10.30:3306/web #${DB_URL}

  jpa:
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: false
    database-platform: org.hibernate.dialect.MariaDBDialect
    generate-ddl: true
    show-sql: true
jwt:
  secret: mysecret.sjb_2023_.qwer1234.Dkagh1234! #${JWT_SECRET}
  token.expired-time-ms: 2592000000 # 30 days